### ISSUE TITLE
Clear history and Clear button

### ISSUE THREAD

**Issue by ghost** [Spedwards/runelite-plugins#1]
Can you add a Clear button and clear History button this is what I imagine it would look like
![mockup](https://user-images.githubusercontent.com/36317465/81233273-56274e80-8fc4-11ea-94f9-678d1ceca84a.png)

**Comment by Spedwards** [comment]
Will look into when I get a minute. Should be simple enough.

**Comment by ghost** [comment]
Cool thanks for the fast reply
