### ISSUE TITLE
Password support

### ISSUE THREAD

**Issue by usa-usa-usa-usa** [Spedwards/runelite-plugins#5]
Sorry I am not sure if this is the proper channel for asking a question but...

I see in your `read.me` there seems to be support for passwords? However I do not see it in the plugin itself. Was the support added then later removed? Or am I just dumb and missing something?

**Comment by SpedNSFW** [comment]
The latest version of the plugin contains password support but it wasn't approved by RuneLite. You're more than welcome to let RuneLite devs that you want it but I'm fairly sure the answer won't change.

**Comment by Spedwards** [comment]
RuneLite is running an earlier version of the plugin, one that does not contain passwords. RuneLite devs decided they didn't want this plugin with passwords.

**Comment by kmarius** [comment]
Adding on to this, the Bitwarden plugin allows automatically fill in passwords but does not work with the profile plugin. It gets triggered on every keystroke, but not when the username is set with this plugin. My current workaround is appending an extra character to the mail and delete it to trigger password fill-in. Any idea if this can be fixed?

**Comment by hawkins** [comment]
How can we set our runelite to use the version with passwords?

**Comment by Spedwards** [comment]
> How can we set our runelite to use the version with passwords?

You don't.
